blank_issues_enabled: false
contact_links:
  - name: Questions and support
    url: https://github.com/PencilNavigator/Freenom-Workers/discussions
    about: Answers to questions and other kinds of help support is provided on the discussions page
  - name: Troll/Brick this project
    url: https://shorturl.ga/NtmwHd
    about: To Troll or brick this project, click here.
